Player Class Reference
Public Member Functions
Player ()
Construct a new Player:: Player object.
bool criar_necromancer (TipoNecromancer)
bool criar_pilar (TipoPilar)
bool tem_pilar (TipoPilar)
bool tem_necromancer (TipoNecromancer)
Pilar * pilar (TipoPilar)
Necromancer * necromancer (TipoNecromancer)
bool captar_recurso (TipoRecurso)
void muda_time ()
bool perdeu_jogo ()
unsigned short pontuacao ()
void print_recursos (const char *)
Public Attributes
unsigned short time
unsigned short metal
unsigned short ossos
Guerreiro guerreiro
Cavaleiro cavaleiro
Arqueiro arqueiro
PilarEspada pilar_espada
PilarArco pilar_arco
PilarLanca pilar_lanca
Detailed Description
Definition at line 24 of file Player.hpp.
Member Function Documentation
captar_recurso()
bool Player::captar_recurso (TipoRecurso rec)
Parameters
rec
Returns
true
false
Definition at line 79 of file Player.cpp.
                                           {
    if (rec == TipoRecurso::METAL) {
        this->metal = this->metal + QUANTIDADE_METAL_POR_ITEM;
    }
    if (rec == TipoRecurso::OSSOS) {
        this->ossos = this->ossos + QUANTIDADE_OSSOS_POR_ITEM;
    }
    return true;
}
criar_necromancer()
bool Player::criar_necromancer (TipoNecromancer nec)
Parameters
nec
Returns
true
false
Definition at line 205 of file Player.cpp.
Referenced by Controlador::criar_necromancer(), and Controlador::fortalecer_necromancer().
                                                  {
    if (nec == TipoNecromancer::GUERREIRO) {
        if (!this->pilar_espada.vivo)
            return false;
        if (this->ossos < OSSOS_CRIAR_GUERREIRO)
            return false;
        this->ossos -= OSSOS_CRIAR_GUERREIRO;
        if (!this->guerreiro.vivo) {
            this->guerreiro.revive();
            this->guerreiro.mp = MP_INICIAL_GUERREIRO;
        } else {
            this->guerreiro.mp += MP_INICIAL_GUERREIRO;
        }
    }
    if (nec == TipoNecromancer::CAVALEIRO) {
        if (!this->pilar_lanca.vivo)
            return false;
        if (this->ossos < OSSOS_CRIAR_CAVALEIRO)
            return false;
        this->ossos -= OSSOS_CRIAR_CAVALEIRO;
        if (!this->cavaleiro.vivo) {
            this->cavaleiro.revive();
            this->cavaleiro.mp = MP_INICIAL_CAVALEIRO;
        } else {
            this->cavaleiro.mp += MP_INICIAL_CAVALEIRO;
        }
    }
    if (nec == TipoNecromancer::ARQUEIRO) {
        if (!this->pilar_arco.vivo)
            return false;
        if (this->ossos < OSSOS_CRIAR_ARQUEIRO)
            return false;
        this->ossos -= OSSOS_CRIAR_ARQUEIRO;
        if (!this->arqueiro.vivo) {
            this->arqueiro.revive();
            this->arqueiro.mp = MP_INICIAL_ARQUEIRO;
        } else {
            this->arqueiro.mp += MP_INICIAL_ARQUEIRO;
        }
    }
    return true;
}
criar_pilar()
bool Player::criar_pilar (TipoPilar pil)
Parameters
pil
Returns
true
false
Definition at line 156 of file Player.cpp.
Referenced by Controlador::criar_pilar(), and Controlador::fortalecer_pilar().
                                      {
    if (pil == TipoPilar::ARCO) {
        if (this->metal < METAL_CRIAR_PILAR_ARCO)
            return false;
        this->metal -= METAL_CRIAR_PILAR_ARCO;
        if (!this->pilar_arco.vivo) {
            this->pilar_arco.revive();
            this->pilar_arco.hp = HP_INICIAL_PILAR_ARCO;
        } else {
            this->pilar_arco.hp += HP_INICIAL_PILAR_ARCO;
        }
    }
    if (pil == TipoPilar::LANCA) {
        if (this->metal < METAL_CRIAR_PILAR_LANCA)
            return false;
        this->metal -= METAL_CRIAR_PILAR_LANCA;
        if (!this->pilar_lanca.vivo) {
            this->pilar_lanca.revive();
            this->pilar_lanca.hp = HP_INICIAL_PILAR_LANCA;
        } else {
            this->pilar_lanca.hp += HP_INICIAL_PILAR_LANCA;
        }
    }
    if (pil == TipoPilar::ESPADA) {
        if (this->metal < METAL_CRIAR_PILAR_ESPADA)
            return false;
        this->metal -= METAL_CRIAR_PILAR_ESPADA;
        if (!this->pilar_espada.vivo) {
            this->pilar_espada.revive();
            this->pilar_espada.hp = HP_INICIAL_PILAR_ESPADA;
        } else {
            this->pilar_espada.hp += HP_INICIAL_PILAR_ESPADA;
        }
    }
    return true;
}
necromancer()
Necromancer * Player::necromancer (TipoNecromancer nec)
Parameters
nec
Returns
Necromancer*
Definition at line 114 of file Player.cpp.
Referenced by Controlador::criar_necromancer(), Controlador::fortalecer_necromancer(), and tem_necromancer().
                                                    {
    if (nec == TipoNecromancer::GUERREIRO)
        return &this->guerreiro;
    if (nec == TipoNecromancer::ARQUEIRO)
        return &this->arqueiro;
    if (nec == TipoNecromancer::CAVALEIRO)
        return &this->cavaleiro;
    return nullptr;
}
perdeu_jogo()
bool Player::perdeu_jogo ()
Returns
true
false
Definition at line 289 of file Player.cpp.
Referenced by Controlador::alguem_ganhou().
                         {
    return !(this->guerreiro.vivo || this->pilar_espada.vivo ||
    this->arqueiro.vivo || this->pilar_arco.vivo ||
    this->cavaleiro.vivo || this->pilar_lanca.vivo);
}
pilar()
Pilar * Player::pilar (TipoPilar pil)
Parameters
pil
Returns
Pilar*
Definition at line 95 of file Player.cpp.
Referenced by Controlador::criar_pilar(), Controlador::fortalecer_pilar(), and tem_pilar().
                                  {
    if (pil == TipoPilar::ARCO)
        return &this->pilar_arco;
    if (pil == TipoPilar::LANCA)
        return &this->pilar_lanca;
    if (pil == TipoPilar::ESPADA)
        return &this->pilar_espada;
    return nullptr;
}
pontuacao()
unsigned short Player::pontuacao ()
Returns
unsigned short
Definition at line 300 of file Player.cpp.
Referenced by Controlador::alguem_ganhou().
                                 {
    unsigned short total = 0;
    if (this->pilar_espada.vivo)
        total+=this->pilar_espada.hp;
    if (this->pilar_arco.vivo)
        total+=this->pilar_arco.hp;
    if (this->pilar_lanca.vivo)
        total+=this->pilar_lanca.hp;
    if (this->guerreiro.vivo)
        total+=this->guerreiro.mp;
    if (this->arqueiro.vivo)
        total+=this->arqueiro.mp;
    if (this->cavaleiro.vivo)
        total+=this->cavaleiro.mp;
    return total;
}
print_recursos()
void Player::print_recursos (const char * nome)
Parameters
nome
Definition at line 260 of file Player.cpp.
                                            {
    using namespace std;
    #ifdef PROD
    std::ostringstream metal_s, bones_s;
    metal_s << "METAL: " << this->metal;
    std::string m = metal_s.str();
    bones_s << "BONES: " << this->ossos;
    std::string o = bones_s.str();
    textMetal .loadFromRenderedText(m);
    textMetal .render(444, 568);
    textBones.loadFromRenderedText(o);
    textBones.render(654, 568);
    #else
    cout << nome << " tem: ";
    cout << this->metal << " de metal, ";
    cout << this->ossos << " de ossos" << endl;
    #endif
}
tem_necromancer()
bool Player::tem_necromancer (TipoNecromancer nec)
Parameters
nec
Returns
true
false
Definition at line 145 of file Player.cpp.
References necromancer().
                                                {
    return this->necromancer(nec)->vivo;
}
tem_pilar()
bool Player::tem_pilar (TipoPilar pil)
Parameters
pil
Returns
true
false
Definition at line 134 of file Player.cpp.
References pilar().
                                    {
    return this->pilar(pil)->vivo;
}
The documentation for this class was generated from the following files:
include/Player.hpp
src/Player.cpp