Mapa Class Reference
Public Member Functions
Mapa (unsigned short, unsigned short)
Construct a new Mapa:: Mapa object.
bool posicao_valida (unsigned short, unsigned short)
bool vazio (unsigned short, unsigned short)
bool inserir (ColocavelEmBloco *, unsigned short, unsigned short)
ColocavelEmBloco * ver (unsigned short, unsigned short)
ColocavelEmBloco * retirar (unsigned short, unsigned short)
Public Attributes
Posicao cursor
MapaDeBlocos mapa
Detailed Description
Definition at line 25 of file Mapa.hpp.
Constructor & Destructor Documentation
Mapa()
Mapa::Mapa (unsigned short X, unsigned short Y)
Construct a new Mapa:: Mapa object.
Parameters
X
Y
Definition at line 24 of file Mapa.cpp.
                                             {
    this->tam_x = X;
    this->tam_y = Y;
    int i, j;
    for (i = 0; i < X; i++)
        for (j = 0; j < Y; j++)
            this->mapa[std::make_pair(i, j)] = Bloco();
}
Member Function Documentation
inserir()
bool Mapa::inserir (ColocavelEmBloco * item, unsigned short X, unsigned short Y)
Parameters
item
X
Y
Returns
true
false
Definition at line 68 of file Mapa.cpp.
References vazio().
Referenced by Controlador::criar_necromancer(), Controlador::criar_pilar(), and Controlador::novo_jogo().
                                                                             {
    if (!this->vazio(X, Y)) return false;
    this->mapa[std::make_pair(X, Y)].preenche(item);
    item->x = X;
    item->y = Y;
    return true;
}
posicao_valida()
bool Mapa::posicao_valida (unsigned short X, unsigned short Y)
Parameters
X
Y
Returns
true
false
Definition at line 41 of file Mapa.cpp.
Referenced by Controlador::gerou_combate(), Controlador::pode_movimentar(), retirar(), vazio(), and ver().
                                                            {
    return X < this->tam_x && Y < this->tam_y;
}
retirar()
ColocavelEmBloco * Mapa::retirar (unsigned short X, unsigned short Y)
Parameters
X
Y
Returns
ColocavelEmBloco*
Definition at line 98 of file Mapa.cpp.
References posicao_valida(), and vazio().
Referenced by Controlador::movimentar().
                                                                  {
    if (this->vazio(X, Y) || !this->posicao_valida(X, Y)) return nullptr;
    ColocavelEmBloco *conteudo = this->mapa[std::make_pair(X, Y)].conteudo;
    this->mapa[std::make_pair(X, Y)].limpa();
    return conteudo;
}
vazio()
bool Mapa::vazio (unsigned short X, unsigned short Y)
Parameters
X
Y
Returns
true
false
Definition at line 53 of file Mapa.cpp.
References posicao_valida().
Referenced by Controlador::criar_necromancer(), Controlador::criar_pilar(), Controlador::gerou_combate(), inserir(), Controlador::matar(), Controlador::movimentar(), Controlador::pode_movimentar(), retirar(), and ver().
                                                   {
    if (!this->posicao_valida(X, Y)) return false;
    return this->mapa[std::make_pair(X, Y)].vazio;
}
ver()
ColocavelEmBloco * Mapa::ver (unsigned short X, unsigned short Y)
Parameters
X
Y
Returns
ColocavelEmBloco*
Definition at line 84 of file Mapa.cpp.
References posicao_valida(), and vazio().
Referenced by Controlador::gerou_combate(), Controlador::matar(), Controlador::movimentar(), Controlador::pode_movimentar(), Controlador::realiza_combate(), and Controlador::verifica_combate().
                                                              {
    if (this->vazio(X, Y) || !this->posicao_valida(X, Y)) return nullptr;
    ColocavelEmBloco *conteudo = this->mapa[std::make_pair(X, Y)].conteudo;
    return conteudo;
}
The documentation for this class was generated from the following files:
include/Mapa.hpp
src/Mapa.cpp