Controlador Class Reference
Public Member Functions
Controlador ()
Construct a new Controlador:: Controlador object.
bool novo_jogo (bool, bool)
bool salvar_jogo (std::string path)
bool carregar_jogo (std::string path)
bool criar_pilar (Player *, TipoPilar, unsigned short, unsigned short)
bool fortalecer_pilar (Player *, TipoPilar)
bool criar_necromancer (Player *, TipoNecromancer, unsigned short, unsigned short)
bool fortalecer_necromancer (Player *, TipoNecromancer)
bool matar (unsigned short, unsigned short)
bool pode_movimentar (Player *, unsigned short, unsigned short, unsigned short, unsigned short)
bool movimentar (Player *, unsigned short, unsigned short, unsigned short, unsigned short)
void processa_jogada ()
bool alguem_ganhou ()
void muda_vez ()
void verifica_combate (unsigned short, unsigned short)
void realiza_combate (unsigned short, unsigned short, unsigned short, unsigned short)
bool gerou_combate (unsigned short, unsigned short, unsigned short)
void print_recursos ()
void print_mapa ()
Public Attributes
Mapa mapa
Player jogador
Player computador
Posicao cursor
std::list< Recurso > recursos
bool jogo_terminou
int ganhou
bool computador_joga
unsigned short vez
int vezes
Detailed Description
Definition at line 26 of file Controlador.hpp.
Member Function Documentation
alguem_ganhou()
bool Controlador::alguem_ganhou ()
Returns
true
false
Definition at line 332 of file Controlador.cpp.
References Player::perdeu_jogo(), and Player::pontuacao().
                                {
    if (this->recursos.size() == 0) {
        if (this->jogador.pontuacao() > this->computador.pontuacao()) {
            this->jogo_terminou = true;
            this->ganhou = 0;
            return true;
        }
        if (this->jogador.pontuacao() < this->computador.pontuacao()) {
            this->jogo_terminou = true;
            this->ganhou = 1;
            return true;
        }
        this->jogo_terminou = true;
        this->ganhou = -1;
        return true;
    }
    if (this->jogador.perdeu_jogo()) {
        this->jogo_terminou = true;
        this->ganhou = 1;
        return true;
    }
    if (this->computador.perdeu_jogo()) {
        this->jogo_terminou = true;
        this->ganhou = 0;
        return true;
    }
    return false;
}
criar_necromancer()
bool Controlador::criar_necromancer (Player * jog, TipoNecromancer nec, unsigned short x, unsigned short y)
Parameters
jog
nec
x
y
Returns
true
false
Definition at line 113 of file Controlador.cpp.
References Player::criar_necromancer(), Mapa::inserir(), Player::necromancer(), and Mapa::vazio().
                                                                                                        {
    if (jog->necromancer(nec)->vivo) return false;
    if (!this->mapa.vazio(x, y)) return false;
    if (!jog->criar_necromancer(nec)) return false;
    this->mapa.inserir(jog->necromancer(nec), x, y);
    return true;
}
criar_pilar()
bool Controlador::criar_pilar (Player * jog, TipoPilar pil, unsigned short x, unsigned short y)
Parameters
jog
pil
x
y
Returns
true
false
Definition at line 94 of file Controlador.cpp.
References Player::criar_pilar(), Mapa::inserir(), Player::pilar(), and Mapa::vazio().
                                                                                            {
    if (jog->pilar(pil)->vivo) return false;
    if (!this->mapa.vazio(x, y)) return false;
    if (!jog->criar_pilar(pil)) return false;
    this->mapa.inserir(jog->pilar(pil), x, y);
    return true;
}
fortalecer_necromancer()
bool Controlador::fortalecer_necromancer (Player * jog, TipoNecromancer nec)
Parameters
jog
nec
Returns
true
false
Definition at line 145 of file Controlador.cpp.
References Player::criar_necromancer(), and Player::necromancer().
                                                                         {
    if (!jog->necromancer(nec)->vivo) return false;
    return jog->criar_necromancer(nec);
}
fortalecer_pilar()
bool Controlador::fortalecer_pilar (Player * jog, TipoPilar pil)
Parameters
jog
pil
Returns
true
false
Definition at line 131 of file Controlador.cpp.
References Player::criar_pilar(), and Player::pilar().
                                                             {
    if (!jog->pilar(pil)->vivo) return false;
    return jog->criar_pilar(pil);
}
gerou_combate()
bool Controlador::gerou_combate (unsigned short time, unsigned short x, unsigned short y)
Parameters
time
x
y
Returns
true
false
Definition at line 243 of file Controlador.cpp.
References Mapa::posicao_valida(), Mapa::vazio(), and Mapa::ver().
Referenced by verifica_combate().
                                                                                       {
    if (!this->mapa.posicao_valida(x, y))
        return false;
    if (this->mapa.vazio(x, y))
        return false;
    if (this->mapa.ver(x, y)->tipo == TipoConteudoBloco::RECURSO)
        return false;
    return this->mapa.ver(x, y)->time != time;
}
matar()
bool Controlador::matar (unsigned short X, unsigned short Y)
Parameters
X
Y
Returns
true
false
Definition at line 159 of file Controlador.cpp.
References Mapa::vazio(), and Mapa::ver().
                                                          {
    if (this->mapa.vazio(X, Y))
        return false;
    if (this->mapa.ver(X, Y)->tipo == TipoConteudoBloco::RECURSO)
        return false;
    ColocavelEmBloco * vitima = this->mapa.retirar(X, Y);
    vitima->mata();
    return true;
}
movimentar()
bool Controlador::movimentar (Player * jog, unsigned short x_orig, unsigned short y_orig, unsigned short x_dest, unsigned short y_dest)
Parameters
jog
x_orig
y_orig
x_dest
y_dest
Returns
true
false
Definition at line 212 of file Controlador.cpp.
References pode_movimentar(), Mapa::retirar(), Mapa::vazio(), and Mapa::ver().
                                                                                                           
                               {
    if (!this->pode_movimentar(jog, x_orig, y_orig, x_dest, y_dest))
        return false;
    ColocavelEmBloco * unidade_movida = this->mapa.retirar(x_orig, y_orig);
    if (!this->mapa.vazio(x_dest, y_dest)) {
        if (this->mapa.ver(x_dest, y_dest)->tipo == TipoConteudoBloco::RECURSO) {
            Recurso * rec = ((Recurso *) mapa.retirar(x_dest, y_dest));
            jog->captar_recurso(rec->tipo_recurso);
            for (std::list<Recurso>::iterator i = this->recursos.begin(); i != this->recursos.end(); ++i)
                if (i->x == x_dest && i->y == y_dest) {
// std::cout << "recurso retirado de " <<i->x << " " << i->y << std::endl;
                    this->recursos.erase(i);
                    break;
                }
        }
    }
    this->mapa.inserir(unidade_movida, x_dest, y_dest);
    this->processa_jogada();
    return true;
}
novo_jogo()
bool Controlador::novo_jogo (bool recursos_aleatorios, bool computador_joga)
Parameters
recursos_aleatorios
computador_joga
Returns
true
false
Definition at line 59 of file Controlador.cpp.
References Mapa::inserir(), and ColocavelEmBloco::setAtivo().
                                                                          {
    this->mapa.inserir(&jogador.guerreiro, X_NECROMANCER_PLAYER, Y_NECROMANCER_PLAYER);
    this->mapa.inserir(&jogador.pilar_espada, X_PILAR_PLAYER, Y_PILAR_PLAYER);
    this->mapa.inserir(&computador.guerreiro, X_NECROMANCER_COMPUTADOR, Y_NECROMANCER_COMPUTADOR);
    this->mapa.inserir(&computador.pilar_espada, X_PILAR_COMPUTADOR, Y_PILAR_COMPUTADOR);
    jogador.guerreiro.setAtivo(true);
    computador.guerreiro.setAtivo(true);
    #ifdef PROD
    ativo_x_jog = X_NECROMANCER_PLAYER;
    ativo_y_jog = Y_NECROMANCER_PLAYER;
    ativo_x_cpu = X_NECROMANCER_COMPUTADOR;
    ativo_y_cpu = Y_NECROMANCER_COMPUTADOR;
    #endif
    if (recursos_aleatorios)
        this->preenche_recursos_iniciais();
    this->computador_joga = computador_joga;
    this->computador.muda_time();
    return true;
}
pode_movimentar()
bool Controlador::pode_movimentar (Player * jog, unsigned short x_orig, unsigned short y_orig, unsigned short x_dest, unsigned short y_dest)
Parameters
jog
x_orig
y_orig
x_dest
y_dest
Returns
true
false
Definition at line 180 of file Controlador.cpp.
References Mapa::posicao_valida(), Mapa::vazio(), and Mapa::ver().
Referenced by movimentar().
                                                                                                           
                                    {
    if (!(this->mapa.posicao_valida(x_orig, y_orig) && this->mapa.
      posicao_valida(x_dest, y_dest)))
        return false;
    if (abs(x_dest - x_orig) > RANGE_MOVIMENTO || abs(y_dest - y_orig) > RANGE_MOVIMENTO)
        return false;
    if (this->mapa.vazio(x_orig, y_orig))
        return false;
    if (this->mapa.ver(x_orig, y_orig)->tipo != TipoConteudoBloco::UNIDADE)
        return false;
    if (this->mapa.ver(x_orig, y_orig)->time != jog->time)
        return false;
    if (this->mapa.vazio(x_dest, y_dest))
        return true;
    if (this->mapa.ver(x_dest, y_dest)->tipo == TipoConteudoBloco::UNIDADE)
        return false;
    if (this->mapa.ver(x_dest, y_dest)->tipo == TipoConteudoBloco::PREDIO)
        return false;
    return true;
}
realiza_combate()
void Controlador::realiza_combate (unsigned short x_atac, unsigned short y_atac, unsigned short x_vit, unsigned short y_vit)
Parameters
x_atac
y_atac
x_vit
y_vit
Definition at line 262 of file Controlador.cpp.
References Mapa::ver().
Referenced by verifica_combate().
                                                                                                           
                      {
    unsigned short dano_golpe;
    std::cout<< "realizando combate em: "<< x_atac << " " << y_atac << " "<< x_vit << " " << y_vit <<
      std::endl;
    Necromancer *atacante = (Necromancer *)this->mapa.ver(x_atac, y_atac);
    ColocavelEmBloco *vitima = this->mapa.ver(x_vit, y_vit);
    TipoNecromancer tipo_vitima_nec = ((Necromancer *) vitima)->tipo_necromancer;
    TipoPilar tipo_vitima_pil = ((Pilar *) vitima)->tipo_pilar;
    switch ((int) this->mapa.ver(x_vit, y_vit)->tipo) {
        case (int) TipoConteudoBloco::UNIDADE:
            dano_golpe = DANO_DE_ATQ * atacante->multiplicador(tipo_vitima_nec);
            if (((Necromancer *) vitima)->mp <= dano_golpe) {
                this->matar(x_vit, y_vit);
                ((Necromancer *) vitima)->mp = 0;
            } else {
                ((Necromancer *) vitima)->mp = ((Necromancer *) vitima)->mp -
      dano_golpe;
            }
            break;
        case (int) TipoConteudoBloco::PREDIO:
            dano_golpe = DANO_DE_ATQ * atacante->multiplicador(tipo_vitima_pil);
            if (((Pilar *) vitima)->hp <= dano_golpe) {
                this->matar(x_vit, y_vit);
            } else {
                ((Pilar *) vitima)->hp = ((Pilar *) vitima)->hp - dano_golpe;
            }
            break;
        default:
            break;
    }
    return;
}
verifica_combate()
void Controlador::verifica_combate (unsigned short x, unsigned short y)
Parameters
x
y
Definition at line 300 of file Controlador.cpp.
References gerou_combate(), realiza_combate(), and Mapa::ver().
                                                                     {
    // std::cout<< "verificando combate em: "<< x << " " << y << std::endl;
    unsigned short time = this->mapa.ver(x, y)->time;
    // Só é combate se tiver na vez do atacante
    if (time != this->vez)
        return;
    // procura adversarios vizinhos e realiza combate se tiver
    for (int i=x-RANGE_COMBATE; i <= x+RANGE_COMBATE; i++)
        for (int j = y-RANGE_COMBATE; j <= y+RANGE_COMBATE; j++)
            if (this->gerou_combate(time, i, j))
                this->realiza_combate(x, y, i, j);
}
The documentation for this class was generated from the following files:
include/Controlador.hpp
src/Controlador.cpp